### ISSUE TITLE
Language ID all the data

### ISSUE THREAD

**Issue by ianbstewart** [ianbstewart/CSS_replication_project#10]
Apply langid to text in dataset collected in #5 and write to separate file (ID to language .csv).

**Comment by ianbstewart** [comment]
Possible TODO: establish lower bound for confidence, i.e. what langid confidence counts as definitely Spanish or Catalan.

**Comment by yuvalpinter** [comment]
90% seems right to me.

Do we discard all other tweets or keep them for some denominator calculation? (I don't think it's necessary considering the original paper's protocol)

**Comment by ianbstewart** [comment]
Done for now, unless we want more Spain data.

Lang IDs stored under data/tweets/archive_Sep-30-16_Oct-31-17_Spain_lang.tsv.
