### ISSUE TITLE
Lang ID for filtered tweets

### ISSUE THREAD

**Issue by ianbstewart** [ianbstewart/CSS_replication_project#15]
Apply langid to filtered tweets and store in separate file. For sanity, we only store the first language (and confidence) returned by langid.classify().

This could reveal a data imbalance: we need a significant amount of Spanish/Catalan for this to work, and some of our hashtags are in English.

**Comment by ianbstewart** [comment]
Used script scripts/data_processing/lang_id_filtered_tweets.py to extract lang IDs at:

/hg190/istewart6/data/tweets/archive_Jan-01-17_Oct-31-17_ref_hashtags_filtered_langid.csv

**Comment by yuvalpinter** [comment]
Statistics:
* 5747 total (about 700 under 0.9 confidence)
* 2542 ES
* 1380 CA
* 1825 other

**Comment by yuvalpinter** [comment]
Problem: there are 11,670 tweets in the total CT dataset (and 5,747 here), and it doesn't look like you filtered based on confidence. @ianbstewart

**Comment by ianbstewart** [comment]
Update: correct numbers in the following files.

11,670 archive_Jan-01-17_Oct-31-17_ref_hashtags_filtered.json
11,670 archive_Jan-01-17_Oct-31-17_ref_hashtags_filtered_langid.csv

**Comment by yuvalpinter** [comment]
4014 Spanish >= 0.9 (4310 total)
2366 Catalan >= 0.9 (2545 total)
All langs 9563 >= 0.9 (11670 total)
