### ISSUE TITLE
Stretch goal 3: explain experiment 2 results

### ISSUE THREAD

**Issue by ianbstewart** [ianbstewart/CSS_replication_project#20]
Look for popular hashtags in control data to explain broadcast effect.

**Comment by yuvalpinter** [comment]
From data extracted into `hashtag_counts.txt`, it doesn't seem there's an overwhelming amount of Catalonia-specific hashtags (these are taken from the 212K user tweets that were used in experiment 2 #9).

In other words, the opposite result we got for experiment 2 is not explainable by the broadcast-to-Catalonia hypothesis.

Bash command:
```sh
cut -f4 /hg190/istewart6/CSS_replication_project/data/tweets/extra_user_tweets/Jan-01-17_Oct-31-17_user_tweets.tsv | awk -F"," '{for (i=1; i<=NF; i++) print $i}' | sort | uniq -c | sort -nr > ../../data/tweets/extra_user_tweets/hashtags_counts.txt
```

**Comment by ianbstewart** [comment]
When we take out the referendum specific hashtags and look at the most popular leftovers in `hashtag_counts.txt`, it looks like there's a lot of activity around Venezuela, which coincidentally held a referendum in July 2017. Analysis [here](../blob/master/scripts/experiment_2/experiment_2_addon.ipynb).
