### ISSUE TITLE
Final report

### ISSUE THREAD

**Issue by ianbstewart** [ianbstewart/CSS_replication_project#21]
Finish writing report and push to repo.

- Make sure we hit all the points [here](https://github.com/jacobeisenstein/gt-css-class/blob/master/grading.md#project-report). 
- Double-check hashtag frequencies in Table 1 (they seem low).
- Get ALL the raw tweet/user counts for experiments.
- Ensure consistent math notation, both within paper and with prior work.

**Comment by yuvalpinter** [comment]
What did we end up doing with the geotagged data? It isn't mentioned in Section 2 at all.

**Comment by ianbstewart** [comment]
It's on the repo but we didn't end up needing it. The original study used the geotagged data for SAGE analysis of Scotland-specific vocab but since we didn't need to do that, we skipped it.
