### ISSUE TITLE
NAACL revisions

### ISSUE THREAD

**Issue by ianbstewart** [ianbstewart/CSS_replication_project#24]
Reviews [here](https://docs.google.com/document/d/1j5jRGLw35L4M-oJF6XjlTkkhM5rTBv7dmOnoXuDNaTk/edit).

Planning to have everything done/ready for Jacob review on April 3.

**Comment by ianbstewart** [comment]
Reviews [here](https://docs.google.com/document/d/1j5jRGLw35L4M-oJF6XjlTkkhM5rTBv7dmOnoXuDNaTk/edit).

**Comment by yuvalpinter** [comment]
There's still some stuff there (also see my comments and strikethroughs in the gdoc):
* "Political hashtags, especially, are often used adversarily. See, i.e, Starbird et al 2017"
* "No empirical results are presented for the prior-art to show the significant differences between Shoemark et al. 2017 work and this current paper."
* "Further explanation of the previous work referenced, particularly the methods and the conclusions would be interesting as a point of comparison and relevant to the motivation of this work."

**Comment by ianbstewart** [comment]
- We added a note about adversarial hashtag use as a limitation in the conclusion.
- I added references to specific numbers in Shoemark et al. throughout the results to address this concern. 
- We can add a more explicit detail in discussion but I thought that we had over-explained Shoemark et al., if anything.

**Comment by yuvalpinter** [comment]
OK cool, I didn't do the diff so I missed these two points.
