### ISSUE TITLE
Assess code-switching

### ISSUE THREAD

**Issue by ianbstewart** [ianbstewart/CSS_replication_project#25]
Manually inspect some (N=100) tweets tagged as either Catalan or Spanish to assess possibility of code-switching.

**Comment by ianbstewart** [comment]
Sampled 50 CA and 50 ES tweets to assess code-switching [here](https://github.com/ianbstewart/CSS_replication_project/blob/master/scripts/data_processing/check_code_switching.ipynb), annotations saved on conair under /hg190/istewart6/CSS_replication_project/data/tweets/CA_ES_sample_tweets_ian_annotated.tsv.

Need @yuvalpinter to download the tweet sample from the notebook, do annotation, and ping me when done so we can compare overlap.

**Comment by yuvalpinter** [comment]
Findings:
* 50 catalan-tagged tweets were all good.
* of 47 spanish-tagged tweets > 0.9 confidence:
  * one was misclassified (completely catalan)
  * two contained single catalan words in a very spanish sentence.

Conclusion: **no phrase-level code-switching** in our sample.
