### ISSUE TITLE
Definitions of p_T and p_X in section 4

### ISSUE THREAD

**Issue by jacobeisenstein** [ianbstewart/CSS_replication_project#37]
"For a user $u$, we denote the proportion of $u$'s referendum-related tweets written in Catalan by $\phu_{T}$, and the proportion of $u$'s control tweets written in Catalan by $\phu_{X}$."

one of these Catalans must be Spanish

**Comment by yuvalpinter** [comment]
No, this is correct. The distinction is between treatment and control conditions.
