### ISSUE TITLE
Create hashtagged dataset (`CT` - Catref Tweets, akin to paper's `IT` Indyref Tweets)

### ISSUE THREAD

**Issue by yuvalpinter** [ianbstewart/CSS_replication_project#5]
After #4 is done, extract all tweets from geotagged dataset with either one of the hashtags (paper had 77,708 at this point, from 26,019 users).

Then filter bots and spammers: 
1. Keep all users with <5 tweets
1. Compute 90th percentile of tweets-with-URL distribution (per user with >=5)
1. Use as threshold and filter out users above it

(In paper this got rid of 11,443 tweets from 1,389 users)

(I think we can skip the final filter used in paper, the one dealing with referendum-ambiguous hashtags)

**Comment by ianbstewart** [comment]
Note: mining with the expanded hashtag set (including lowercased, no-accent hashtags) stored at

/hg190/istewart6/CSS_replication_project/data/expanded_fixed_hashtags.csv

**Comment by ianbstewart** [comment]
Current counts:

Expanded hashtags=4164 (data/tweets/archive_Sep-30-16_Oct-31-17_ES_tweets_ref_hashtags.json)

Expanded hashtags, all lowercase/accent combos=5586 (data/tweets/archive_Sep-30-16_Oct-31-17_ES_tweets_ref_hashtags_fixed.json)

I'm going to query the archive files for the full expanded/fixed hashtag set in hopes of getting more tweets.

**Comment by ianbstewart** [comment]
Extracted all tweets from archive that contain at least one referendum hashtag.

Count=190,060

I'm now going to remove all spam following the same procedure as Shoemark et al.

**Comment by ianbstewart** [comment]
Filter stats:

Pre-filter: 190,060 tweets 106,587 users
Hashtag filter: 79,326 tweets 60,146 users
Original (non-RT) filter: 12,663 tweets 10,678 users
Low-URL filter: 11,670 tweets 10,498 users

This is much lower than the final Shoemark et al. dataset (59,664 tweets 18,589 users), and I haven't even looked at how many of the tweets are usable (Spanish versus Catalan). We may need to re-run the hashtag collection with a wider range of hashtags, collected based on cooccurrence, OR sample more tweets from the archive for the users that we already have.
