### ISSUE TITLE
EXPERIMENT 2 - do users tweet more in Catalan depending on tweet context?

### ISSUE THREAD

**Issue by yuvalpinter** [ianbstewart/CSS_replication_project#9]
Dependency: #5 

Since we don't have individual word variables, we need to rethink the metrics. This is part of the issue.

1. Collect users who tweeted in either ES or CA in both a hashtagged tweet and a non-hashtagged tweet (should be practically all users).
1. Compute rates of CA tweets per user conditioned on
    1. Referendum-hashtagged
    1. Non-referendum-hashtagged (broadcast audience)
    1. Not hashtagged.
1. The paper used one-sample t-test for the overall diff. We will use (?).

**Comment by ianbstewart** [comment]
Mining extra user tweets based on users in data/user_groups.csv with script

scripts/data_processing/mine_extra_user_tweets.sh

**Comment by ianbstewart** [comment]
Running tests in scripts/experiment_2/experiment_2.ipynb.

**Comment by ianbstewart** [comment]
Results are in!

Test 1 = All controls
Users = 775
Referendum tweets = 890
Control tweets = 31,154

mean d_u = 0.031
std err = 0.011
t-stat =2.839
p-val = 0.00464

Test 2 = Controls with hashtags
Users = 550
Referendum tweets = 656
Control tweets = 13,956

mean d_u = 0.014
std err = 0.011
t-stat = 1.230
p-val = 0.219

**Conclusion**: 

People are more likely to use Catalan in referendum-related tweets than in non-referendum tweets, but not more likely to use Catalan in referendum-related tweets than in hashtag-inclusive non-referendum tweets.
